[project]
name = "llama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fairscale>=0.4.13",
    "fire>=0.7.0",
    "sentencepiece>=0.2.0",
    "torch>=2.8.0",
    "torchao>=0.12.0",
    "torchtune>=0.6.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
